cutoff_len: 2048
dataset: zen_nano
dataset_dir: /Users/z/work/zoo/gym/data
do_train: true
finetuning_type: lora
gradient_accumulation_steps: 8
gradient_checkpointing: true
learning_rate: 0.0001
logging_steps: 10
lora_alpha: 32
lora_dropout: 0.05
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
model_name_or_path: Qwen/Qwen3-4B-Instruct
num_train_epochs: 3
output_dir: ./output/zen-nano
per_device_train_batch_size: 2
plot_loss: true
quantization_bit: 4
save_steps: 100
stage: sft
template: qwen3
warmup_ratio: 0.1
